### ISSUE TITLE
Review MMTabBarView's _delegate

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/MMTabBarView#19]
Currently, MMTabBarView's  property "delegate" is declared weak, but is implemented strong.
https://github.com/ViennaRSS/MMTabBarView/blob/c922356b2d9ea10c716da255fb2f58c336b000ca/MMTabBarView/MMTabBarView/MMTabBarView.h#L91-L95

https://github.com/ViennaRSS/MMTabBarView/blob/c922356b2d9ea10c716da255fb2f58c336b000ca/MMTabBarView/MMTabBarView/MMTabBarView.m#L113-L115

Need to decide on a design : weak or nullable strong.

Related : https://github.com/MiMo42/MMTabBarView/issues/76 if weak implementation https://github.com/MiMo42/MMTabBarView/commit/9e03810415250ed7e55cc8576a6373c1f1d22bf3 is chosen

**Comment by barijaona** [comment]
In pull request #22 , the property is declared nullable strong

**Comment by TAKeanice** [comment]
see my comment in #22 . I consider weak the most expected and safe choice. Unexpected deallocation due to not retaining the delegate will happen less often as memory leaks due to retain cycles, and will probably be discovered more easily in testing.

**Comment by barijaona** [comment]
Cf. pull request #23 : we chose to implement MMTabBarView's delegate property as weak, in order to limit risks of retain cycles.
