### ISSUE TITLE
Raise deployment target of demo app to macOS 10.13

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/MMTabBarView#42]
To build the demo app with Xcode 14.3, I have to raise its deployment target to macOS 10.13.

_Originally posted by @barijaona in https://github.com/ViennaRSS/MMTabBarView/issues/40#issuecomment-1514701838_

**Comment by TAKeanice** [comment]
Then we need to adapt the Readme. Is it still compatible with older XCodes and MacOS though?
